"""descripción de la migración

Revision ID: 16fe296f240f
Revises: 4fad92974b97
Create Date: 2024-04-25 10:41:30.122818

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '16fe296f240f'
down_revision = '4fad92974b97'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('actividad', schema=None) as batch_op:
        batch_op.add_column(sa.Column('persona_encargada', sa.String(length=100), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('actividad', schema=None) as batch_op:
        batch_op.drop_column('persona_encargada')

    # ### end Alembic commands ###
