"""descripción de la migración

Revision ID: 2e55ca1091a7
Revises: 3abd9efdba6c
Create Date: 2024-05-10 10:40:56.465604

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2e55ca1091a7'
down_revision = '3abd9efdba6c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('actividad', schema=None) as batch_op:
        batch_op.add_column(sa.Column('proyecto_id', sa.Integer(), nullable=False))
        batch_op.create_foreign_key(None, 'proyecto', ['proyecto_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('actividad', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('proyecto_id')

    # ### end Alembic commands ###
