"""descripción de la migración

Revision ID: 584213097cea
Revises: fd27574ac8ea
Create Date: 2024-06-25 22:47:49.867470

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '584213097cea'
down_revision = 'fd27574ac8ea'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('registro', schema=None) as batch_op:
        batch_op.add_column(sa.Column('imagen_url', sa.String(length=200), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('registro', schema=None) as batch_op:
        batch_op.drop_column('imagen_url')

    # ### end Alembic commands ###
