"""descripción de la migración

Revision ID: bad704b6835d
Revises: e97360991199
Create Date: 2024-06-12 13:56:06.157439

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bad704b6835d'
down_revision = 'e97360991199'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('registro', schema=None) as batch_op:
        batch_op.add_column(sa.Column('estado', sa.String(length=20), nullable=False))
        batch_op.add_column(sa.Column('inhabilitado', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('registro', schema=None) as batch_op:
        batch_op.drop_column('inhabilitado')
        batch_op.drop_column('estado')

    # ### end Alembic commands ###
