"""descripción de la migración

Revision ID: fa10a9aaeb08
Revises: 2e55ca1091a7
Create Date: 2024-05-10 10:46:10.919636

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'fa10a9aaeb08'
down_revision = '2e55ca1091a7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('actividad', schema=None) as batch_op:
        batch_op.alter_column('proyecto_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('actividad', schema=None) as batch_op:
        batch_op.alter_column('proyecto_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False)

    # ### end Alembic commands ###
